default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: localhost
  port: 5432
  database: blackops_development
  username: blackops
  password: <%= ENV['BLACKOPS_DATABASE_PASSWORD'] %>

test: &test
  <<: *default
  database: blackops_test
  host: localhost
  port: 5432
  username: blackops
  password: <%= ENV['BLACKOPS_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: blackops_production
  username: blackops
  password: <%= ENV['BLACKOPS_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
